### ISSUE TITLE
Does not respect TIMBRE_LEVEL compile time var

### ISSUE THREAD

**Issue by ianconsolata** [fzakaria/slf4j-timbre#26] opened 2017-06-21 22:49 UTC
In a project with no timbre config, but only a TIMBRE_LEVEL var, timbre respects the level but other java libraries using slf-4j do not.

**Comment by rufoa** [comment] 2017-06-22 04:45
Thanks for the report.

I believe the root cause is that [`(levels level)`](https://github.com/fzakaria/slf4j-timbre/blob/9054f9f3a85fef4260d19117bcc0ac0225bfecab/src/slf4j_timbre/adapter.clj#L107) is not a compile-time constant so timbre cannot elide log statements at compile-time based on its value.

I'll think how we might overcome this, potentially by using macros, and hope to have a fix ASAP.

**Comment by rufoa** [comment] 2017-06-22 22:33
@jungziege please check this is fixed in `0.3.7-SNAPSHOT`, available on clojars

**Comment by rufoa** [comment] 2017-06-27 18:39
Assuming this works

Released as `0.3.7`

**Closed as completed by rufoa** 2017-06-27 18:39 UTC
