### ISSUE TITLE
slf4j-timbre causes mysterious failure due to encore and reader

### ISSUE THREAD

**Issue by kenrestivo** [fzakaria/slf4j-timbre#9] opened 2015-12-26 23:14 UTC
I got bit by this as well. It actually took me hours to try to track it down, and I never did figure it out. But thankfully someone finally did:

http://yogthos.net/posts/2015-12-26-AOTGotchas.html

I suppose maybe the library instead of :aot :all could exclude some namespaces from AOT? Or is this impossible to fix?

**Comment by fzakaria** [comment] 2015-12-27 00:13
I'm going to close as this is a duplicate of https://github.com/fzakaria/slf4j-timbre/issues/8
Pretty good to see Yogthos's blog.
I think the only solution is to wait for 4.15 and just update.

Shame of this AOT problem as I do like the Timbre library but it makes the choice vs Log4J implementation.

**Closed as completed by fzakaria** 2015-12-27 00:13 UTC
